/* 부모들의 이름 */
CREATE OR REPLACE VIEW PARENTS_WITH_NAMES AS (
    SELECT P.PID, P.FHID, FH.NAME AS FHNAME, P.MHID, MH.NAME AS MHNAME, P.CHILDCOUNT
    FROM (PARENTS P
        LEFT OUTER JOIN HUMAN FH ON (P.FHID = FH.HID)
        LEFT OUTER JOIN HUMAN MH ON (P.MHID = MH.HID))
);

/* 사람과 그 사람 부모의 이름 */
CREATE OR REPLACE VIEW HUMAN_WITH_PARENTS AS (
    SELECT H.*, PN.FHID, PN.FHNAME, PN.MHID, PN.MHNAME, PN.CHILDCOUNT
        FROM HUMAN H LEFT OUTER JOIN PARENTS_WITH_NAMES PN ON (H.PID = PN.PID)
);

/* 사람과 그 사람의 배우자 */
CREATE OR REPLACE VIEW HUMAN_WITH_MATE AS (
    SELECT H.*, MATE_P.PID AS MATE_P_PID, MATE_H.HID AS MATE_HID, MATE_H.NAME AS MATE_NAME,
            MATE_H.SEX AS MATE_SEX, MATE_H.BIRTH AS MATE_BIRTH, MATE_H.DEATH AS MATE_DEATH, MATE_H.PID AS MATE_PID
        FROM HUMAN H
            LEFT OUTER JOIN PARENTS MATE_P ON (H.HID = MATE_P.FHID OR H.HID = MATE_P.MHID)
            LEFT OUTER JOIN HUMAN MATE_H ON (
                (H.HID <> MATE_P.FHID AND MATE_P.FHID = MATE_H.HID)
                    OR (H.HID <> MATE_P.MHID AND MATE_P.MHID = MATE_H.HID)
            )
);
