/* 친가 부계 찾기 1 */
SELECT 1 AS "LEVEL", HH1.HID AS HID, HH1.NAME AS NAME, HH1.PID AS PID, P1.FHID AS FHID, P1.MHID AS MHID
    FROM HUMAN HH1 LEFT OUTER JOIN PARENTS P1 ON (HH1.PID = P1.PID)
    WHERE HH1.NAME = '여자'
UNION
SELECT LEVEL, H.HID AS HID, H.NAME AS NAME, H.PID AS PID, P.FHID AS FHID, P.MHID AS MHID
    FROM HUMAN H LEFT OUTER JOIN PARENTS P ON (H.PID = P.PID)
    START WITH HID = (
        SELECT HH.HID
            FROM HUMAN HH LEFT OUTER JOIN PARENTS P2 ON (HH.PID = P2.PID)
            WHERE HH.NAME = '여자' AND (P2.FHID IS NOT NULL OR (P2.FHID IS NULL AND P2.MHID IS NULL))
    )
    CONNECT BY NOCYCLE PRIOR FHID = HID OR (FHID IS NULL AND PRIOR MHID = HID);

/* 친가 부계 찾기 2 */
SELECT 1 AS "LEVEL", HH1.HID AS HID, HH1.NAME AS NAME, HH1.PID AS PID, P1.FHID AS FHID, P1.MHID AS MHID
    FROM HUMAN HH1 LEFT OUTER JOIN PARENTS P1 ON (HH1.PID = P1.PID)
    WHERE HH1.NAME = '외할아버지'
UNION
SELECT LEVEL, H.HID AS HID, H.NAME AS NAME, H.PID AS PID, P.FHID AS FHID, P.MHID AS MHID
    FROM HUMAN H LEFT OUTER JOIN PARENTS P ON (H.PID = P.PID)
    START WITH HID = (
        SELECT HH.HID
            FROM HUMAN HH LEFT OUTER JOIN PARENTS P2 ON (HH.PID = P2.PID)
            WHERE HH.NAME = '외할아버지' AND (P2.FHID IS NOT NULL OR (P2.FHID IS NULL AND P2.MHID IS NULL))
    )
    CONNECT BY NOCYCLE PRIOR FHID = HID OR (FHID IS NULL AND PRIOR MHID = HID);

/* 외가 부계 찾기 */
SELECT 1 AS "LEVEL", HH1.HID AS HID, HH1.NAME AS NAME, HH1.PID AS PID, P1.FHID AS FHID, P1.MHID AS MHID
    FROM HUMAN HH1 LEFT OUTER JOIN PARENTS P1 ON (HH1.PID = P1.PID)
    WHERE HH1.NAME = '여자'
UNION
SELECT LEVEL+1 AS "LEVEL", H.HID AS HID, H.NAME AS NAME, H.PID AS PID, P.FHID AS FHID, P.MHID AS MHID
    FROM HUMAN H LEFT OUTER JOIN PARENTS P ON (H.PID = P.PID)
    START WITH HID = (
        SELECT P2.MHID
            FROM HUMAN HH2, PARENTS P2
            WHERE HH2.NAME = '여자' AND HH2.PID = P2.PID
    )
    CONNECT BY NOCYCLE PRIOR FHID = HID OR (FHID IS NULL AND PRIOR MHID = HID);

/* 배우자 찾기 */
WITH TEMP_MATE_HID AS (
    SELECT H.HID AS HID, H.NAME AS NAME, H.SEX, H.BIRTH, MATE_P.PID AS MATE_P_PID,
            CASE MATE_P.FHID WHEN H.HID THEN MATE_P.MHID ELSE MATE_P.FHID END MATE_HID
        FROM HUMAN H LEFT OUTER JOIN PARENTS MATE_P ON (H.HID = MATE_P.FHID OR H.HID = MATE_P.MHID)
)
SELECT TMH.*, MH.NAME AS MATE_NAME, MH.SEX AS MATE_SEX
    FROM TEMP_MATE_HID TMH LEFT OUTER JOIN HUMAN MH ON (TMH.MATE_HID = MH.HID)
    ORDER BY TMH.BIRTH;
